INSERT INTO BD006.DEPARTMENTS (DEPARTMENT_NAME, MANAGER_FIRST_NAME, MANAGER_LAST_NAME)
VALUES ('Cardiology', 'John', 'Smith');

INSERT INTO BD006.DEPARTMENTS (DEPARTMENT_NAME, MANAGER_FIRST_NAME, MANAGER_LAST_NAME)
VALUES ('Orthopedics', 'Mary', 'Johnson');

INSERT INTO BD006.DEPARTMENTS (DEPARTMENT_NAME, MANAGER_FIRST_NAME, MANAGER_LAST_NAME)
VALUES ('Pediatrics', 'Robert', 'Davis');

INSERT INTO BD006.DEPARTMENTS (DEPARTMENT_NAME, MANAGER_FIRST_NAME, MANAGER_LAST_NAME)
VALUES ('Neurology', 'Emily', 'Jones');

INSERT INTO BD006.DEPARTMENTS (DEPARTMENT_NAME, MANAGER_FIRST_NAME, MANAGER_LAST_NAME)
VALUES ('Oncology', 'Michael', 'Miller');

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('David', 'Anderson', TO_DATE('2022-05-15', 'YYYY-MM-DD'), 120000, 21);

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('Jessica', 'Brown', TO_DATE('2023-02-20', 'YYYY-MM-DD'), 110000, 22);

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('Christopher', 'Lee', TO_DATE('2021-08-10', 'YYYY-MM-DD'), 130000, 23);

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('Banjo', 'Jumping', TO_DATE('2021-08-27', 'YYYY-MM-DD'), 1300, 23);

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('Banjoe', 'Jumpingrt', TO_DATE('2021-08-23', 'YYYY-MM-DD'), 13000, 23);

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('Sophia', 'Taylor', TO_DATE('2024-01-02', 'YYYY-MM-DD'), 125000, 24);

INSERT INTO BD006.DOCTORS (DOCTOR_FIRST_NAME, DOCTOR_LAST_NAME, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES ('Daniel', 'Wang', TO_DATE('2022-11-18', 'YYYY-MM-DD'), 115000, 25);

INSERT INTO BD006.NURSES (FIRST_NAME, LAST_NAME, SPECIALIZATION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Laura', 'Williams', 'Cardiology', 75000, TO_DATE('2023-05-15', 'YYYY-MM-DD'), 21);

INSERT INTO BD006.NURSES (FIRST_NAME, LAST_NAME, SPECIALIZATION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Laurawer', 'Williamseee', 'Cardiology', 750000, TO_DATE('2023-05-12', 'YYYY-MM-DD'), 21);

INSERT INTO BD006.NURSES (FIRST_NAME, LAST_NAME, SPECIALIZATION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Daniel', 'Moore', 'Orthopedics', 72000, TO_DATE('2022-12-20', 'YYYY-MM-DD'), 22);

INSERT INTO BD006.NURSES (FIRST_NAME, LAST_NAME, SPECIALIZATION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Ava', 'Baker', 'Pediatrics', 70000, TO_DATE('2021-07-10', 'YYYY-MM-DD'), 23);

INSERT INTO BD006.NURSES (FIRST_NAME, LAST_NAME, SPECIALIZATION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Liam', 'Jones', 'Neurology', 78000, TO_DATE('2023-01-02', 'YYYY-MM-DD'), 24);

INSERT INTO BD006.NURSES (FIRST_NAME, LAST_NAME, SPECIALIZATION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Sophie', 'Davis', 'Oncology', 76000, TO_DATE('2022-10-18', 'YYYY-MM-DD'), 25);

INSERT INTO BD006.MEDICAL_EQUIPMENT (EQUIPMENT_NAME, DEPARTMENT_ID, AVAILABLE_FOR_USE)
VALUES ('X-ray Machine', 21, 10);

INSERT INTO BD006.MEDICAL_EQUIPMENT (EQUIPMENT_NAME, DEPARTMENT_ID, AVAILABLE_FOR_USE)
VALUES ('MRI Scanner', 22, 8);

INSERT INTO BD006.MEDICAL_EQUIPMENT (EQUIPMENT_NAME, DEPARTMENT_ID, AVAILABLE_FOR_USE)
VALUES ('RMN Scanner', 22, 10);

INSERT INTO BD006.MEDICAL_EQUIPMENT (EQUIPMENT_NAME, DEPARTMENT_ID, AVAILABLE_FOR_USE)
VALUES ('Ultrasound Device', 23, 12);

INSERT INTO BD006.MEDICAL_EQUIPMENT (EQUIPMENT_NAME, DEPARTMENT_ID, AVAILABLE_FOR_USE)
VALUES ('ECG Machine', 24, 15);

INSERT INTO BD006.MEDICAL_EQUIPMENT (EQUIPMENT_NAME, DEPARTMENT_ID, AVAILABLE_FOR_USE)
VALUES ('Operating Table', 25, 5);

INSERT INTO BD006.ADMINISTRATIVE_BRANCH_PER_DEPARTMENT (FIRST_NAME, LAST_NAME, POSITION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Alex', 'Wilson', 'Manager', 80000, TO_DATE('2022-04-15', 'YYYY-MM-DD'), 21);

INSERT INTO BD006.ADMINISTRATIVE_BRANCH_PER_DEPARTMENT (FIRST_NAME, LAST_NAME, POSITION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Grace', 'Brown', 'Supervisor', 70000, TO_DATE('2022-11-20', 'YYYY-MM-DD'), 22);

INSERT INTO BD006.ADMINISTRATIVE_BRANCH_PER_DEPARTMENT (FIRST_NAME, LAST_NAME, POSITION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Brian', 'Taylor', 'Coordinator', 65000, TO_DATE('2023-03-10', 'YYYY-MM-DD'), 23);

INSERT INTO BD006.ADMINISTRATIVE_BRANCH_PER_DEPARTMENT (FIRST_NAME, LAST_NAME, POSITION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Jessica', 'Clark', 'Administrator', 60000, TO_DATE('2021-09-05', 'YYYY-MM-DD'), 24);

INSERT INTO BD006.ADMINISTRATIVE_BRANCH_PER_DEPARTMENT (FIRST_NAME, LAST_NAME, POSITION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Samuel', 'Smith', 'Office Assistant', 50000, TO_DATE('2023-01-20', 'YYYY-MM-DD'), 25);

INSERT INTO BD006.ADMINISTRATIVE_BRANCH_PER_DEPARTMENT (FIRST_NAME, LAST_NAME, POSITION, SALARY, HIRE_DATE, DEPARTMENT_ID)
VALUES ('Lee', 'Smith', 'Administrator', 500000, TO_DATE('2023-01-23', 'YYYY-MM-DD'), 25);

INSERT INTO BD006.INVENTORY_EQUIPMENT (QUANTITY, CONDITION, BUYING_DATE, EQUIPMENT_ID)
VALUES (5, 'New', TO_DATE('2022-01-15', 'YYYY-MM-DD'), 23);

INSERT INTO BD006.INVENTORY_EQUIPMENT (QUANTITY, CONDITION, BUYING_DATE, EQUIPMENT_ID)
VALUES (3, 'Used', TO_DATE('2022-07-20', 'YYYY-MM-DD'), 24);

INSERT INTO BD006.INVENTORY_EQUIPMENT (QUANTITY, CONDITION, BUYING_DATE, EQUIPMENT_ID)
VALUES (8, 'New', TO_DATE('2023-04-05', 'YYYY-MM-DD'), 25);

INSERT INTO BD006.INVENTORY_EQUIPMENT (QUANTITY, CONDITION, BUYING_DATE, EQUIPMENT_ID)
VALUES (2, 'Used', TO_DATE('2021-12-10', 'YYYY-MM-DD'), 26);

INSERT INTO BD006.INVENTORY_EQUIPMENT (QUANTITY, CONDITION, BUYING_DATE, EQUIPMENT_ID)
VALUES (6, 'Broken', TO_DATE('2023-09-25', 'YYYY-MM-DD'), 27);

INSERT INTO BD006.PATIENTS (PATIENT_FIRST_NAME, PATIENT_LAST_NAME, DATE_OF_BIRTH, BLOOD_TYPE, MEDICAL_INSURANCE, DOCTOR_ID)
VALUES ('John', 'Doe', TO_DATE('1985-03-12', 'YYYY-MM-DD'), 'A', 'cass', 25);

INSERT INTO BD006.PATIENTS (PATIENT_FIRST_NAME, PATIENT_LAST_NAME, DATE_OF_BIRTH, BLOOD_TYPE, MEDICAL_INSURANCE, DOCTOR_ID)
VALUES ('Alice', 'Smith', TO_DATE('1990-07-25', 'YYYY-MM-DD'), 'B', 'private', 26);

INSERT INTO BD006.PATIENTS (PATIENT_FIRST_NAME, PATIENT_LAST_NAME, DATE_OF_BIRTH, BLOOD_TYPE, MEDICAL_INSURANCE, DOCTOR_ID)
VALUES ('Robert', 'Johnson', TO_DATE('1982-11-05', 'YYYY-MM-DD'), 'AB', 'cass', 27);

INSERT INTO BD006.PATIENTS (PATIENT_FIRST_NAME, PATIENT_LAST_NAME, DATE_OF_BIRTH, BLOOD_TYPE, MEDICAL_INSURANCE, DOCTOR_ID)
VALUES ('Emily', 'Brown', TO_DATE('1995-05-18', 'YYYY-MM-DD'), '0', 'private', 28);

INSERT INTO BD006.PATIENTS (PATIENT_FIRST_NAME, PATIENT_LAST_NAME, DATE_OF_BIRTH, BLOOD_TYPE, MEDICAL_INSURANCE, DOCTOR_ID)
VALUES ('Michael', 'Wilson', TO_DATE('1988-09-30', 'YYYY-MM-DD'), 'A', 'cass', 28);

INSERT INTO BD006.PATIENT_HISTORY (MODIFICATION_DATE, MODIFICATION, PATIENT_ID)
VALUES (TO_DATE('2022-03-10', 'YYYY-MM-DD'), 'Admitted for routine checkup.', 9);

INSERT INTO BD006.PATIENT_HISTORY (MODIFICATION_DATE, MODIFICATION, PATIENT_ID)
VALUES (TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'Underwent surgery for appendicitis', 10);

INSERT INTO BD006.PATIENT_HISTORY (MODIFICATION_DATE, MODIFICATION, PATIENT_ID)
VALUES (TO_DATE('2022-07-05', 'YYYY-MM-DD'), 'Received vaccinations for flu and pneumonia', 11);

INSERT INTO BD006.PATIENT_HISTORY (MODIFICATION_DATE, MODIFICATION, PATIENT_ID)
VALUES (TO_DATE('2023-04-20', 'YYYY-MM-DD'), 'Diagnosed with diabetes, prescribed medication', 12);

INSERT INTO BD006.PATIENT_HISTORY (MODIFICATION_DATE, MODIFICATION, PATIENT_ID)
VALUES (TO_DATE('2021-10-15', 'YYYY-MM-DD'), 'Discharged after successful cancer treatment', 13);

INSERT INTO BD006.DRUG_INFO (SIDE_EFFECTS, PRICE)
VALUES ('Usual Side Effects', 10.99);

INSERT INTO BD006.DRUG_INFO (SIDE_EFFECTS, PRICE)
VALUES ('No Side Effects', 5.49);

INSERT INTO BD006.DRUG_INFO (SIDE_EFFECTS, PRICE)
VALUES ('Mild Drowsiness', 8.99);

INSERT INTO BD006.DRUG_INFO (SIDE_EFFECTS, PRICE)
VALUES ('Digestive Issues', 12.99);

INSERT INTO BD006.DRUG_INFO (SIDE_EFFECTS, PRICE)
VALUES ('Headache and Nausea', 15.99);

INSERT INTO BD006.DRUG_INFO (SIDE_EFFECTS, PRICE)
VALUES ('Headache', 16.99);

INSERT INTO BD006.DRUGS (DRUG_NAME, AVAILABLE_FOR_USE, DEPARTMENT_ID, MANUFACTURER, INFO_ID)
VALUES ('Drug A', 100, 21, 'PharmaCorp', 22);

INSERT INTO BD006.DRUGS (DRUG_NAME, AVAILABLE_FOR_USE, DEPARTMENT_ID, MANUFACTURER, INFO_ID)
VALUES ('Drug B', 50, 22, 'HealthMeds', 23);

INSERT INTO BD006.DRUGS (DRUG_NAME, AVAILABLE_FOR_USE, DEPARTMENT_ID, MANUFACTURER, INFO_ID)
VALUES ('Vaccine X', 200, 23, 'VaxCo', 24);

INSERT INTO BD006.DRUGS (DRUG_NAME, AVAILABLE_FOR_USE, DEPARTMENT_ID, MANUFACTURER, INFO_ID)
VALUES ('Insulin Y', 30, 24, 'DiabPharma', 25);

INSERT INTO BD006.DRUGS (DRUG_NAME, AVAILABLE_FOR_USE, DEPARTMENT_ID, MANUFACTURER, INFO_ID)
VALUES ('Chemotherapy Drug Z', 10, 25, 'OncologyMeds', 26);

INSERT INTO BD006.DRUG_TRANSACTIONS (QUANTITY_BOUGHT, ACQUISITION_DATE, SELLER, DRUG_ID)
VALUES (50, TO_DATE('2023-01-15', 'YYYY-MM-DD'), 'PharmaSupplier', 20);

INSERT INTO BD006.DRUG_TRANSACTIONS (QUANTITY_BOUGHT, ACQUISITION_DATE, SELLER, DRUG_ID)
VALUES (30, TO_DATE('2023-02-20', 'YYYY-MM-DD'), 'HealthWholesaler', 21);

INSERT INTO BD006.DRUG_TRANSACTIONS (QUANTITY_BOUGHT, ACQUISITION_DATE, SELLER, DRUG_ID)
VALUES (100, TO_DATE('2023-03-10', 'YYYY-MM-DD'), 'MediDistributor', 22);

INSERT INTO BD006.DRUG_TRANSACTIONS (QUANTITY_BOUGHT, ACQUISITION_DATE, SELLER, DRUG_ID)
VALUES (20, TO_DATE('2023-04-05', 'YYYY-MM-DD'), 'PharmaExpress', 23);

INSERT INTO BD006.DRUG_TRANSACTIONS (QUANTITY_BOUGHT, ACQUISITION_DATE, SELLER, DRUG_ID)
VALUES (10, TO_DATE('2023-05-15', 'YYYY-MM-DD'), 'HealthSupplies', 24);